CREATE DATABASE parking_management;
USE parking_management;

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `bcrypt`
--

-- --------------------------------------------------------

--
-- Table structure for table `usuario`
--

--
-- Dumping data for table `usuario`
--



--
-- Indexes for dumped tables
--

--
-- Indexes for table `usuario`
--
-- -----------------------------------TABLAS---------------------

CREATE TABLE `USUARIO`
(
    `IDENTIFICACION` int(10) NOT NULL PRIMARY KEY COMMENT 'Se espera una cédula con formato: 101230123',
    `NOMBRE` varchar(30) NOT NULL COMMENT 'Por ejemplo: roberto.escobaraguero',
    `CONTRASEÑA` varchar(64) NOT NULL COMMENT '64 caracteres esperando un SHA256',
    `CORREO` VARCHAR(50) NOT NULL COMMENT 'SE ESPERABA UNA DIRECCION DE CORREO',
    `NUMERO_TELEFONO` VARCHAR(15) NOT NULL COMMENT 'SE ESPERABA UN NUMERO DE TELEFONO',
    `DIRECCION` VARCHAR(150) NOT NULL COMMENT 'SE ESPERABA UNA DIRECCION RESIDENCIAL',
    `FECHA_REGISTRO` VARCHAR(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `USUARIO` VALUES (855625, "Breiner", "$2a$10$F4689HKJ5JTKBA7AGNKoNeOHi4nqsJgftihsm07F.n97LRcc7fpwe", "breynersmartinezmunoz@gmail.com", "3138619952", "CRA 14 #8_26", "15/05/25" );
INSERT INTO `USUARIO` VALUES (12345, "Julian", "$2a$10$F4689HKJ5JTKBA7AGNKoNeOHi4nqsJgftihsm07F.n97LRcc7fpwe", "Julian@gmail.com", "3138619952", "CRA 14 #8_26", "15/05/25" );

SELECT*FROM USUARIO;


CREATE TABLE `ADMINISTRADOR`
(
    `IDENTIFICACION` int(10) NOT NULL PRIMARY KEY COMMENT 'Se espera una cédula con formato: 101230123'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
INSERT INTO `ADMINISTRADOR` VALUES (855625 );


ALTER TABLE ADMINISTRADOR ADD CONSTRAINT FK_IDENTIFICACION_ADMINISTRADOR FOREIGN KEY (IDENTIFICACION) REFERENCES USUARIO(IDENTIFICACION);
SELECT*FROM ADMINISTRADOR;



CREATE TABLE `CLIENTE`
(
    `IDENTIFICACION` int(10) NOT NULL PRIMARY KEY COMMENT 'Se espera una cédula con formato: 101230123'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
INSERT INTO `CLIENTE` VALUES (12345);


ALTER TABLE CLIENTE ADD CONSTRAINT FK_IDENTIFICACION_CLIENTE FOREIGN KEY (IDENTIFICACION) REFERENCES USUARIO(IDENTIFICACION);

CREATE TABLE `VEHICULO`
(

    `ID_VEHICULO` int(10) NOT NULL PRIMARY KEY ,
    `IDENTIFICACION` INT(10) NOT NULL  COMMENT 'Se espera una cédula con formato: 101230123',
    `PLACA_VEHICULO` VARCHAR(10) NOT NULL,
    `ID_TIPO_VEHICULO` int(10) NOT NULL,
    `MARCA_VEHICULO`  VARCHAR(20) NOT NULL,
    `COLOR_VEHICULO`  VARCHAR(20) NOT NULL,
    `TARJETA_PROPIEDAD`  VARCHAR(200) NOT NULL,
    `HORA_ENTRADA`  VARCHAR(20) NOT NULL,
    `HORA_SALIDA`   VARCHAR(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
ALTER TABLE `VEHICULO` ADD CONSTRAINT FK_IDENTIFICACION_CLIENTE FOREIGN KEY (IDENTIFICACION) REFERENCES USUARIO(IDENTIFICACION);
ALTER TABLE  `VEHICULO` ADD CONSTRAINT FK_ID_TIPO_VEHICULO FOREIGN KEY (ID_TIPO_VEHICULO) REFERENCES TIPO_VEHICULO(ID_TIPO_VEHICULO);


CREATE TABLE `TIPO_VEHICULO`
(
    `ID_TIPO_VEHICULO`  int(10) NOT NULL PRIMARY KEY,
    `TIPO_VEHICULO` VARCHAR(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


CREATE TABLE `ESPACIO`
(
    `ID_ESPACIO` INT(10) NOT NULL PRIMARY KEY ,
    `NUMERO_ESPACIO` VARCHAR(20) NOT NULL,
    `ESTADO_ESPACIO` VARCHAR(20) NOT NULL,
    `TIPO_ESPACIO` VARCHAR(60) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `TARIFA`
(
    `ID_TARIFA` INT(10) NOT NULL PRIMARY KEY,
    `ID_TIPO_VEHICULO` INT(10) NOT NULL,
    `VALOR_HORA` INT(5) NOT NULL,
    `VALOR_DIA` INT(5) NOT NULL,
    `VALOR_MES` INT(5) NOT NULL,
    `VALOR_AÑO` INT(5) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
ALTER TABLE  `TARIFA` ADD CONSTRAINT FK_ID_TIPO_VEHICULO FOREIGN KEY (ID_TIPO_VEHICULO)  REFERENCES TIPO_VEHICULO(ID_TIPO_VEHICULO);


CREATE TABLE `RESERVA_ESPACIO`
(
    `ID_RESERVA_ESPACIO` INT(10) NOT NULL PRIMARY KEY,
    `IDENTIFICACION`  INT(10) NOT NULL  COMMENT 'Se espera una cédula con formato: 101230123',
    `ID_ESPACIO`	INT(10) NOT NULL,
    `FECHA_INICIO`	VARCHAR(100),
    `FECHA_FIN`		VARCHAR(100),
    `ESTADO`		VARCHAR(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
ALTER TABLE `RESERVA_ESPACIO` ADD CONSTRAINT FK_IDENTIFICACION_CLIENTE FOREIGN KEY (IDENTIFICACION) REFERENCES USUARIO(IDENTIFICACION);
ALTER TABLE  `RESERVA_ESPACIO` ADD CONSTRAINT	FK_ID_ESPACIO FOREIGN KEY (ID_ESPACIO) REFERENCES ESPACIO(ID_ESPACIO);


CREATE TABLE `TICKET`
(
    `ID_TICKET` INT(10) NOT NULL PRIMARY KEY,
    `ID_VEHICULO` INT(10) NOT NULL,
    `IDENTIFICACION`  INT(10) NOT NULL  COMMENT 'Se espera una cédula con formato: 101230123',
    `IDENTIFICACION` int(10) NOT NULL  COMMENT 'Se espera una cédula con formato: 101230123',
    `ID_ESPACIO` INT(10) NOT NULL,
    `HORA_ENTRADA`	VARCHAR(100),
    `HORA_SALIDA` VARCHAR(100),
    `VALOR_TOTAL` INT(5) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
ALTER TABLE `TICKET` ADD CONSTRAINT FK_IDENTIFICACION_CLIENTE FOREIGN KEY (IDENTIFICACION) REFERENCES USUARIO(IDENTIFICACION);
ALTER TABLE `TICKET` ADD CONSTRAINT FK_IDENTIFICACION_ADMINISTRADOR FOREIGN KEY (IDENTIFICACION) REFERENCES ADMINISTRADOR(IDENTIFICACION);
ALTER TABLE  `TICKET` ADD CONSTRAINT	FK_ID_ESPACIO FOREIGN KEY (ID_ESPACIO) REFERENCES ESPACIO(ID_ESPACIO);
ALTER TABLE  `TICKET` ADD CONSTRAINT	FK_ID_VEHICULO FOREIGN KEY (ID_VEHICULO) REFERENCES VEHICULO(ID_VEHICULO);



CREATE TABLE `PAGO`
(
    `ID_PAGO` INT(10) NOT NULL PRIMARY KEY,
    `ID_TICKET` INT(10) NOT NULL,
    `FECHA_PAGO`	VARCHAR(100),
    `MONTO` INT(10) NOT NULL,
    `ID_METODO_PAGO` INT(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
ALTER TABLE  `PAGO` ADD CONSTRAINT	FK_ID_TICKET FOREIGN KEY (ID_TICKET) REFERENCES TICKET(ID_TICKET);
ALTER TABLE  `PAGO` ADD CONSTRAINT	FK_ID_METODO_PAGO FOREIGN KEY (ID_METODO_PAGO) REFERENCES  METODO_PAGO(ID_METODO_PAGO);



CREATE TABLE `METODO_PAGO`
(
    `ID_METODO_PAGO` INT(10) NOT NULL,
    `METODO_PAGO` VARCHAR(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;

SELECT*FROM  `USUARIO`;
SELECT*FROM ADMINISTRADOR;

-- ------------------------------- INSERCCION DE DATOS-----------------




-- ------------------------------- ALTERACION DE TABLAS ----------------------

-- Renombraiento de tabla ADMINISTRADOR
ALTER TABLE Administrador RENAME ADMINISTRADOR;

--  Cambio de nombre de la columna IdentificacionAdministrador a IDENTIFICACION
ALTER TABLE ADMINISTRADOR
    CHANGE IdentificacionAdministrador IDENTIFICACION  int(9) NOT NULL COMMENT 'Se espera una cédula con formato: 101230123';

-- Cambio de nombre de la columna nameAdmin a NOMBRE
ALTER TABLE ADMINISTRADOR
    CHANGE nameAdmin NOMBRE varchar(30) NOT NULL COMMENT 'Por ejemplo: roberto.escobaraguero';

ALTER TABLE ADMINISTRADOR
    CHANGE password CONTRASEÑA varchar(64) NOT NULL COMMENT '64 caracteres esperando un SHA256';


ALTER TABLE CLIENTE
    MODIFY COLUMN `FECHA_REGISTRO` VARCHAR(100);

ALTER TABLE CLIENTE
    MODIFY COLUMN `NUMERO_TELEFONO` VARCHAR(15);



ALTER TABLE `usuario`
    ADD PRIMARY KEY (`idUsuario`);
COMMIT;

ALTER TABLE `Administrador`
    ADD PRIMARY KEY (`IdentificacionAdministrador`);
COMMIT;

-- -------------------------  CONSULTAS -------------------------------
